name: Run BDD Tests and Publish Cucumber Reports

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Cucumber tests and generate HTML report
        run: |
          npx cucumber-js --format html:cucumber-report.html

      - name: Deploy cucumber-report.html to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true
          destination_dir: .
          force_orphan: true
          cname: ""
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
